source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

project 'TSMessages'

target 'TSMessages' do
  pod "TSMessages", :path => "../"
end

target 'Tests' do
  pod "TSMessages", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
